version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.26
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: hugo -v -s ~/project/
      - run:
          name: "Install stuff 1a"
          command: sudo apt-get install python-pip python-dev
      - run:
          name: "Install stuff 1b"
          command: sudo pip install python-dateutil
      - run:
          name: "Install stuff 2"
          command: sudo pip install --no-deps s3cmd
      - run:
          name: "Install stuff 3"
          command: echo "access_key = $AWS_ACCESS_KEY_ID" >> ~/.s3cfg
      - run:
          name: "Install stuff 4"
          command: echo "secret_key = $AWS_SECRET_ACCESS_KEY" >> ~/.s3cfg
      - run:
          name: "Install stuff 5"
          command: aws configure set preview.cloudfront true
      - deploy:
          command: |
            s3cmd sync --config=.s3cfg --no-mime-magic --delete-removed -P -M -r public/ s3://loudervoice-website/
            aws cloudfront create-invalidation --distribution-id $PROD_CF_DIST --paths "/*"